# -*- coding: utf-8 -*-
"""DL_4_google.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JBHPoS2csekS0Q912RcJiIKcuF0lH1Dj
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train_df = pd.read_csv("/content/gdrive/MyDrive/Prac_datasets/Google_Stock_Price_Train.csv")

train_df.head()

train_df.dtypes

train_df['Close']= train_df['Close'].str.replace(",", '').astype(float)
train_df['Volume']= train_df['Volume'].str.replace(",", '').astype(float)

train_df.dtypes



plt.figure(figsize = (6,4))
train_df['Open'].plot()
plt.xlabel(None)
plt.ylabel("price")
plt.title('Closing prices of the google stock price')

train_df.plot( 'Date' , 'Close' )

train_df.plot('Date', "Volume")

train_df=train_df.iloc[:,1:2].values

train_df.shape



from sklearn.preprocessing import MinMaxScaler



mms = MinMaxScaler()
train_df = mms.fit_transform(train_df)

x_train = train_df[0:1257]
y_train = train_df[1:1258]

x_train = np.reshape(x_train, (1257,1,1))

from keras.models import Sequential
from keras.layers import Dense, LSTM

model= Sequential()

model.add(LSTM(16, activation = 'sigmoid', input_shape=(None,1)))
model.add(Dense(8))
model.add(Dense(1))
model.compile(optimizer='adam', loss= 'mean_squared_error')
model.fit(x_train, y_train, batch_size=42, epochs = 200)

test_df=pd.read_csv("/content/gdrive/MyDrive/Prac_datasets/Google_Stock_Price_Test.csv")

real_stock_price = test_df.iloc[:,1:2].values

inputs = real_stock_price
inputs = mms.transform(inputs)
#inputs = np.reshape(inputs, (20,1,1))
predicted= model.predict(inputs)
predicted = mms.inverse_transform(predicted)

plt.plot(real_stock_price, color = 'red')
plt.plot(predicted, color = 'blue')